export default {
  DUMMY: 'DUMMY',
  CLEAR_DUMMY: 'CLEAR_DUMMY',
  LOGIN: 'LOGIN_API',
  CLEAR_LOGIN: 'CLEAR_LOGIN_API',
  SEND_OTP: 'SEND_OTP',
  CLEAR_SEND_OTP: 'CLEAR_SEND_OTP',
  VERIFY_OTP: 'VERIFY_OTP',
  CLEAR_VERIFY_OTP: 'CLEAR_VERIFY_OTP',
  FORGET_PASSWORD_VERIFY_EMAIL: 'FORGET_PASSWORD_VERIFY_EMAIL',
  CLEAR_FORGET_PASSWORD_VERIFY_EMAIL: 'CLEAR_FORGET_PASSWORD_VERIFY_EMAIL',
  VERIFY_FORGOT_PASSWORD: 'VERIFY_FORGOT_PASSWORD',
  CLEAR_VERIFY_FORGOT_PASSWORD: 'CLEAR_VERIFY_FORGOT_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CLEAR_RESET_PASSWORD: 'CLEAR_RESET_PASSWORD',
  EMAIL_VERIFY_FORGOT_PASSWORD: 'EMAIL_VERIFY_FORGOT_PASSWORD',
  CLEAR_EMAIL_VERIFY_FORGOT_PASSWORD: 'CLEAR_EMAIL_VERIFY_FORGOT_PASSWORD',
  OTP_VERIFICATION_FORGOT_PASSWORD: 'OTP_VERIFICATION_FORGOT_PASSWORD',
  CLEAR_OTP_VERIFICATION_FORGOT_PASSWORD: 'CLEAR_OTP_VERIFICATION_FORGOT_PASSWORD',
  GET_ALL_GRADES: 'GET_ALL_GRADES',
  CLEAR_GET_ALL_GRADES: 'CLEAR_GET_ALL_GRADES',
  GET_ALL_COUNTRIES: 'GET_ALL_COUNTRIES',
  CLEAR_GET_ALL_COUNTRIES: 'CLEAR_GET_ALL_COUNTRIES',
  GET_ALL_STATES: 'GET_ALL_STATES',
  CLEAR_GET_ALL_STATES: 'CLEAR_GET_ALL_STATES',
  GET_ALL_DISTRICTS: 'GET_ALL_DISTRICTS',
  CLEAR_GET_ALL_DISTRICTS: 'CLEAR_GET_ALL_DISTRICTS`',
  SIGNUP_STUDENT: 'SIGNUP_STUDENT',
  CLEAR_SIGNUP_STUDENT: 'CLEAR_SIGNUP_STUDENT',
  SEND_OTP_SIGNUP: 'SEND_OTP_SIGNUP',
  CLEAR_SEND_OTP_SIGNUP: 'CLEAR_SEND_OTP_SIGNUP',
  VERIFY_OTP_SIGNUP: 'VERIFY_OTP_SIGNUP',
  CLEAR_VERIFY_OTP_SIGNUP: 'CLEAR_VERIFY_OTP_SIGNUP',
  MOBILE_VERIFICATION: 'MOBILE_VERIFICATION',
  CLEAR_MOBILE_VERIFICATION: 'CLEAR_MOBILE_VERIFICATION',
  MOBILE_VERIFICATION_OTP_SEND: 'MOBILE_VERIFICATION_OTP_SEND',
  CLEAR_MOBILE_VERIFICATION_OTP_SEND: 'CLEAR_MOBILE_VERIFICATION_OTP_SEND',

  /* Dashboard */
  DASHBOARD_COUNT: 'DASHBOARD_COUNT',
  CLEAR_DASHBOARD_COUNT: 'CLEAR_DASHBOARD_COUNT',

  /* Packages */
  GET_ALL_PACKAGES_DATA: 'GET_ALL_PACKAGES_DATA',
  CLEAR_GET_ALL_PACKAGES_DATA: 'CLEAR_GET_ALL_PACKAGES_DATA',
  GET_PACKAGES_DATA_ID: 'GET_PACKAGES_DATA_ID',
  CLEAR_GET_PACKAGES_DATA_ID: 'CLEAR_GET_PACKAGES_DATA_ID',
  GET_ADD_ON_PACKAGES_DATA: 'GET_ADD_ON_PACKAGES_DATA',
  CLEAR_GET_ADD_ON_PACKAGES_DATA: 'CLEAR_GET_ADD_ON_PACKAGES_DATA',

  /* Test Process */
  GET_ALL_TEST_PROCESS_DATA: 'GET_ALL_TEST_PROCESS_DATA',
  CLEAR_GET_ALL_TEST_PROCESS_DATA: 'CLEAR_GET_ALL_TEST_PROCESS_DATA',
  GET_ALL_QUESTIONS_BY_ID: 'GET_ALL_QUESTIONS_BY_ID',
  CLEAR_GET_ALL_QUESTIONS_BY_ID: 'CLEAR_GET_ALL_QUESTIONS_BY_ID',

  QUESTIONS: 'QUESTIONS',
  CLEAR_QUESTIONS: 'CLEAR_QUESTIONS',

  SUBMIT_OPTION: 'SUBMIT_OPTION',
  CLEAR_SUBMIT_OPTION: 'CLEAR_SUBMIT_OPTION',

  FINISH_TEST: 'FINISH_TEST',
  CLEAR_FINISH_TEST: 'CLEAR_FINISH_TEST',

  LOGOUT: 'LOGOUT',
  CLEAR_LOGOUT: 'CLEAR_LOGOUT',

  VIEW_PROFILE: 'VIEW_PROFILE',
  CLEAR_VIEW_PROFILE: 'CLEAR_VIEW_PROFILE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CLEAR_CHANGE_PASSWORD: 'CLEAR_CHANGE_PASSWORD',

  GET_ALL_BOARDS_DATA: 'GET_ALL_BOARDS_DATA',
  CLEAR_GET_ALL_BOARDS_DATA: 'CLEAR_GET_ALL_BOARDS_DATA',

  GET_ACTIVE_PACKAGES: 'GET_ACTIVE_PACKAGES',
  CLEAR_GET_ACTIVE_PACKAGES: 'CLEAR_GET_ACTIVE_PACKAGES',

  GET_ADD_ON_PACKAGES: 'GET_ADD_ON_PACKAGES',
  CLEAR_GET_ADD_ON_PACKAGES: 'CLEAR_GET_ADD_ON_PACKAGES',

  GET_PACKAGE_HISTORY_LIST: 'GET_PACKAGE_HISTORY_LIST',
  CLEAR_GET_PACKAGE_HISTORY_LIST: 'CLEAR_GET_PACKAGE_HISTORY_LIST',

  DOWNLOAD_INVOICE: 'DOWNLOAD_INVOICE',
  CLEAR_DOWNLOAD_INVOICE: 'CLEAR_DOWNLOAD_INVOICE',

  GET_OTHER_PACKAGES: 'GET_OTHER_PACKAGES',
  CLEAR_GET_OTHER_PACKAGES: 'CLEAR_GET_OTHER_PACKAGES',

  PURCHASED_PACKAGE: 'PURCHASED_PACKAGE',
  CLEAR_PURCHASED_PACKAGE: 'CLEAR_PURCHASED_PACKAGE',

  // Test-assessement module
  GET_ALL_COMPLETED_TEST: 'GET_ALL_COMPLETED_TEST',
  CLEAR_GET_ALL_COMPLETED_TEST: 'CLEAR_GET_ALL_COMPLETED_TEST',

  GET_ASSESSMENT_DATA: 'GET_ASSESSMENT_DATA',
  CLEAR_GET_ASSESSMENT_DATA: 'CLEAR_GET_ASSESSMENT_DATA',

  GET_TEST_CATEGORY_BY_ID_DATA: 'GET_TEST_CATEGORY_BY_ID_DATA',
  CLEAR_GET_TEST_CATEGORY_BY_ID_DATA: 'CLEAR_GET_TEST_CATEGORY_BY_ID_DATA',

  // Interest Test
  GET_INTEREST_TEST_DETAILS: 'GET_INTEREST_TEST_DETAILS',
  CLEAR_GET_INTEREST_TEST_DETAILS: 'CLEAR_GET_INTEREST_TEST_DETAILS',

  // Package Purchase
  PACKAGE_PURCHASE_SUCCESS: 'PACKAGE_PURCHASE_SUCCESS',
  CLEAR_PACKAGE_PURCHASE_SUCCESS: 'CLEAR_PACKAGE_PURCHASE_SUCCESS',

  // Counsellor
  GET_ALL_AVAILABLE_SLOTS: 'GET_ALL_AVAILABLE_SLOTS',
  CLEAR_GET_ALL_AVAILABLE_SLOTS: 'CLEAR_GET_ALL_AVAILABLE_SLOTS',

  GET_ALL_FILTERED_COUNSELLOR: 'GET_ALL_FILTERED_COUNSELLOR',
  CLEAR_GET_ALL_FILTERED_COUNSELLOR: 'CLEAR_GET_ALL_FILTERED_COUNSELLOR',

  GET_ALL_SESSION_HISTORY: 'GET_ALL_SESSION_HISTORY',
  CLEAR_GET_ALL_SESSION_HISTORY: 'CLEAR_GET_ALL_SESSION_HISTORY',

  GET_ALL_COUNSELLOR_DETAILS: 'GET_ALL_COUNSELLOR_DETAILS',
  CLEAR_GET_ALL_COUNSELLOR_DETAILS: 'CLEAR_GET_ALL_COUNSELLOR_DETAILS',

  GET_ALL_COUNSELLOR_AVAILABLE_SLOTS: 'GET_ALL_COUNSELLOR_AVAILABLE_SLOTS',
  CLEAR_GET_ALL_COUNSELLOR_AVAILABLE_SLOTS: 'CLEAR_GET_ALL_COUNSELLOR_AVAILABLE_SLOTS',

  GENERATE_REPORT: 'GENERATE_REPORT',
  CLEAR_GENERATE_REPORT: 'CLEAR_GENERATE_REPORT',

  BOOK_SESSION: 'BOOK_SESSION',
  CLEAR_BOOK_SESSION: 'CLEAR_BOOK_SESSION',

  SESSION_DETAILS: 'SESSION_DETAILS',
  CLEAR_SESSION_DETAILS: 'CLEAR_SESSION_DETAILS',

  GET_GRAPH_DATA: 'GET_GRAPH_DATA',
  CLEAR_GET_GRAPH_DATA: 'CLEAR_GET_GRAPH_DATA',

  COUNSELLOR_RESCHEDULE: 'COUNSELLOR_RESCHEDULE',
  CLEAR_COUNSELLOR_RESCHEDULE: 'CLEAR_COUNSELLOR_RESCHEDULE',

  CANCEL_SESSION: 'CANCEL_SESSION',
  CLEAR_CANCEL_SESSION: 'CLEAR_CANCEL_SESSION',

  REPORT_SESSION: 'REPORT_SESSION',
  CLEAR_REPORT_SESSION: 'CLEAR_REPORT_SESSION',

  GET_ALL_SCHOOL_DETAILS: 'GET_ALL_SCHOOL_DETAILS',
  CLEAR_GET_ALL_SCHOOL_DETAILS: 'CLEAR_GET_ALL_SCHOOL_DETAILS',

  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CLEAR_UPDATE_PROFILE: 'CLEAR_UPDATE_PROFILE',

  RATINGS: 'RATINGS',
  CLEAR_RATINGS: 'CLEAR_RATINGS',

  GET_ALL_SCHOOLS: 'GET_ALL_SCHOOLS',
  CLEAR_GET_ALL_SCHOOLS: 'CLEAR_GET_ALL_SCHOOLS'

}
